kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.name}}
  labels:
    release: prometheus-stack
spec:
  endpoints:
    - interval: 15s
      port: metrics
  namespaceSelector:
    matchNames:
      - {{.Values.name}}
  selector:
    matchLabels:
      k8s-app: {{.Values.name}}
