kind: Service
apiVersion: v1
metadata:
  name: {{.Values.name}}
  labels:
    k8s-app: {{.Values.name}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    k8s-app: {{.Values.name}}
  type: ClusterIP
  sessionAffinity: None
