{{ if .Values.pos.install }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pos-ng11
  namespace: default
  labels:
    k8s-app: pos-ng11
spec:
  selector:
    matchLabels:
      k8s-app: pos-ng11
  template:
    metadata:
      name: pos-ng11
      labels:
        k8s-app: pos-ng11
    spec:
      containers:
        - name: pos-ng11
          image: {{ .Values.pos.image }}
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: pos-ng11
  namespace: default
  labels:
    k8s-app: pos-ng11
spec:
  ports:
    - name: pos-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: pos-ng11
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: pos-ng11-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressNginx.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - {{ .Values.pos.host }}
      secretName: elektrawebpos-cert
  rules:
    - host: {{ .Values.pos.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: pos-ng11
                port:
                  number: 80
  {{ end }}
