{{ if .Values.sql.runCreationScripts }}
kind: Job
apiVersion: batch/v1
metadata:
  name: sql-create-ddlevents
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-90"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: initial-creator
          image: {{ .Values.sql.creationScriptImage }}
          args:
            - /Action:Publish
            - /SourceFile:/elektrawebdb/DDLEVENTS/DDLEVENTS.dacpac
            - /TargetServerName:tcp:{{ .Values.sql.connection.server }},{{ .Values.sql.connection.port }}
            - /TargetUser:{{ .Values.sql.connection.user }}
            - /TargetPassword:{{ .Values.sql.connection.password }}
            - /TargetDatabaseName:{{ .Values.dbNames.DDLEVENTS }}
            - /TargetTrustServerCertificate:True
            - /SourceTrustServerCertificate:True
{{ end }}
