{{ if .Values.sql.runCreationScripts }}
kind: Job
apiVersion: batch/v1
metadata:
  name: sql-create-emds-archive
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-25"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: initial-creator
          image: {{ .Values.sql.creationScriptImage }}
          args:
            - /Action:Publish
            - /SourceFile:/elektrawebdb/EMDS_ARCHIVE/EMDS_ARCHIVE.dacpac
            - /TargetServerName:tcp:{{ .Values.sql.connection.server }},{{ .Values.sql.connection.port }}
            - /TargetUser:{{ .Values.sql.connection.user }}
            - /TargetPassword:{{ .Values.sql.connection.password }}
            - /TargetDatabaseName:{{ .Values.dbNames.EMDS_ARCHIVE }}
            - /Variables:DDLEVENTS={{ .Values.dbNames.DDLEVENTS }}
            - /Variables:EMDS={{ .Values.dbNames.EMDS }}
            - /TargetTrustServerCertificate:True
            - /SourceTrustServerCertificate:True
{{ end }}
